DROP TABLE COMPUTERS;
DROP TABLE VISITORS;

CREATE TABLE VISITORS(
VISITOR_ID NUMBER(5) NOT NULL,
VISITOR_NAME VARCHAR2(20) NOT NULL,
VISITOR_FACULTY VARCHAR2(20) NOT NULL,
VISITOR_RULE NUMBER(6) NOT NULL,
PC_ID VARCHAR2(10) NOT NULL,
BORROW_ID VARCHAR2(10) NOT NULL,
FINES_COLLECTED NUMBER(5,2) NOT NULL,
CONSTRAINT VISITORS_pk PRIMARY KEY (VISITOR_ID)
);

INSERT INTO VISITORS (VISITOR_ID, VISITOR_NAME, VISITOR_FACULTY, VISITOR_RULE, PC_ID, BORROW_ID, FINES_COLLECTED)
VALUES(15510,'EVA', 'EDUCATION',123456,'KTNV-3X6W','AB23',6);

INSERT INTO VISITORS (VISITOR_ID, VISITOR_NAME, VISITOR_FACULTY, VISITOR_RULE, PC_ID, BORROW_ID, FINES_COLLECTED)
VALUES(15517,'SAMIA', 'SCIENCE',748583,'GDSS-673K','RE43',8);

INSERT INTO VISITORS (VISITOR_ID, VISITOR_NAME, VISITOR_FACULTY, VISITOR_RULE, PC_ID, BORROW_ID, FINES_COLLECTED)
VALUES(14231,'TULI', 'ARTS',872343,'JKDG-874M','KF14',9);

INSERT INTO VISITORS (VISITOR_ID, VISITOR_NAME, VISITOR_FACULTY, VISITOR_RULE, PC_ID, BORROW_ID, FINES_COLLECTED)
VALUES(15222,'JIDNY', 'CLASSICS',256343,'FDIH-U443','AG87',11);

INSERT INTO VISITORS (VISITOR_ID, VISITOR_NAME, VISITOR_FACULTY, VISITOR_RULE, PC_ID, BORROW_ID, FINES_COLLECTED)
VALUES(11231,'SIAM', 'ENGINEERING',374788,'UHTD-47RT','PA32',13);

INSERT INTO VISITORS (VISITOR_ID, VISITOR_NAME, VISITOR_FACULTY, VISITOR_RULE, PC_ID, BORROW_ID, FINES_COLLECTED)
VALUES(14121,'RUMI', 'COMMERCE',215476,'HDGF-64T4','JS74',15);

INSERT INTO VISITORS (VISITOR_ID, VISITOR_NAME, VISITOR_FACULTY, VISITOR_RULE, PC_ID, BORROW_ID, FINES_COLLECTED)
VALUES(13445,'HAZERA', 'GRADUATE STUDIES',198376,'OIYF-3784','AH26',20);



CREATE TABLE COMPUTERS(
PC_ID VARCHAR2(10) NOT NULL,
BRAND_NAME VARCHAR2(20) NOT NULL,
WINDOWS_VERSION VARCHAR2(10) NOT NULL,
CPU_MODEL VARCHAR2(20) NOT NULL,
RAM_ID VARCHAR2(10) NOT NULL,
USER_ID VARCHAR2(10) NOT NULL,
lIBRARY_ID VARCHAR2(6) NOT NULL,
CONSTRAINT PC_ID PRIMARY KEY (PC_ID)
);


INSERT INTO COMPUTERS (PC_ID, BRAND_NAME, WINDOWS_VERSION, CPU_MODEL, RAM_ID, USER_ID, lIBRARY_ID)
VALUES('KTNV-3X6W','DELL', 'WINDOWS-10','Intel',9201,'HK100158',123456);

INSERT INTO COMPUTERS (PC_ID, BRAND_NAME, WINDOWS_VERSION, CPU_MODEL, RAM_ID, USER_ID, lIBRARY_ID)
VALUES('GDSS-673K','HP', 'WINDOWS-10','Intel',4226,'LG534UA',345732);

INSERT INTO COMPUTERS (PC_ID, BRAND_NAME, WINDOWS_VERSION, CPU_MODEL, RAM_ID, USER_ID, lIBRARY_ID) 
VALUES('JKDG-874M','LENOVO', 'WINDOWS-10','Intel',1355,'X169607',246535);

INSERT INTO COMPUTERS (PC_ID, BRAND_NAME, WINDOWS_VERSION, CPU_MODEL, RAM_ID, USER_ID, lIBRARY_ID) 
VALUES('FDIH-U443','APPLE', 'macOS-11','M1 Chip',3265,'JBU3470',165342);

INSERT INTO COMPUTERS (PC_ID, BRAND_NAME, WINDOWS_VERSION, CPU_MODEL, RAM_ID, USER_ID, lIBRARY_ID) 
VALUES('UHTD-47RT','MICROSOFT', 'WINDOWS-8','Intel',9367,'PC50365',784432);

INSERT INTO COMPUTERS (PC_ID, BRAND_NAME, WINDOWS_VERSION, CPU_MODEL, RAM_ID, USER_ID, lIBRARY_ID) 
VALUES('HDGF-64T4','ASUS', 'WINDOWS-10','Intel',6537,'UC123456',983446);

INSERT INTO COMPUTERS (PC_ID, BRAND_NAME, WINDOWS_VERSION, CPU_MODEL, RAM_ID, USER_ID, lIBRARY_ID) 
VALUES('OIYF-3784','ACER', 'WINDOWS-10','Intel',7843,'FP23568',783332);


